include(InstallRequiredSystemLibraries)

set(CPACK_PACKAGE_NAME "lab07-solver")
set(CPACK_PACKAGE_VENDOR "kanadya07")
set(CPACK_PACKAGE_CONTACT "kanadya07@mail.ru")
set(CPACK_PACKAGE_VERSION_MAJOR ${LAB07_VERSION_MAJOR})
set(CPACK_PACKAGE_VERSION_MINOR ${LAB07_VERSION_MINOR})
set(CPACK_PACKAGE_VERSION_PATCH ${LAB07_VERSION_PATCH})
set(CPACK_PACKAGE_VERSION_TWEAK ${LAB07_VERSION_TWEAK})
set(CPACK_PACKAGE_VERSION ${LAB07_VERSION})
set(CPACK_PACKAGE_DESCRIPTION_FILE ${CMAKE_CURRENT_SOURCE_DIR}/DESCRIPTION)
set(CPACK_PACKAGE_DESCRIPTION_SUMMARY "Solver application package")
set(CPACK_RESOURCE_FILE_LICENSE ${CMAKE_CURRENT_SOURCE_DIR}/LICENSE)
set(CPACK_RESOURCE_FILE_README ${CMAKE_CURRENT_SOURCE_DIR}/README.md)

set(CPACK_SOURCE_GENERATOR "TGZ;ZIP")
set(CPACK_GENERATOR "TGZ")

include(CPack)
